spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false

app:
  rabbitmq:
    consumer:
      enabled: ${APP_RABBITMQ_CONSUMER_ENABLED:false}
  messaging:
    enabled: ${APP_MESSAGING_ENABLED:true}
    consumer-enabled: ${APP_MESSAGING_CONSUMER_ENABLED:true}
    queue-name: ${APP_MESSAGING_QUEUE_NAME:quote-notification-events}
    endpoint: ${AWS_ENDPOINT:http://localhost:4566}
    region: ${AWS_REGION:us-east-1}
    poll-delay-ms: ${APP_MESSAGING_POLL_DELAY_MS:3000}
  service-token:
    public-key: ${APP_SERVICE_TOKEN_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApSeG/JJIj4r/5XeZhatc1ddBqedj5gbhIh4WzuZ5euRbGyqK0X2gHOhHBrvKOWLnJ/sMfRaeuKItCF5j6TIjOxTkOXgbiim8EppQVac25BNMaqrDvAK/0sPpXphba8Q2VW0AACoT2XsG70AgIzWFIWcAAvgQHaa8kz9Baneto2BOSOz6vByRzlAxikFzR9CTN02O4JeaOdvDPNjxyLaxiRMD+YW1HxLEPIR0Bt3dl5kNxyVMu31xq7Mmdcqpu2BbrKbDDzBkMPSBpW2l+3SsqFzk1z4cwuOS0ZpzyMDoA1ca7t5F2BzOpcT2rVZoAZeDyXeZ0UmeGAhDyzdEqlTwhQIDAQAB}
    issuer: ${APP_SERVICE_TOKEN_ISSUER:mortgage-loan-api}
    audience: ${APP_SERVICE_TOKEN_AUDIENCE:notification-service}
    scope: ${APP_SERVICE_TOKEN_SCOPE:notification:write}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8089
